name: comm_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  provider: ^6.1.1

  cupertino_icons: ^1.0.8

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  cloud_functions: ^6.0.6
  url_launcher: ^6.1.10
  intl: ^0.20.2

  image_picker: ^1.0.7
  http: ^1.2.1
  crypto: ^3.0.3
  path: ^1.9.0
  path_provider: ^2.1.2
  gal: ^2.3.0
  qr_flutter: ^4.1.0


  local_auth: ^2.1.6
  fl_chart: ^0.64.0
  flutter_localizations:
    sdk: flutter
  share_plus: ^7.2.1
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^17.2.2
  mobile_scanner: ^3.5.2
  timeago: ^3.7.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
