name: comm_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  provider: ^6.1.1

  cupertino_icons: ^1.0.8

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.6.0
  cloud_functions: ^4.7.4
  url_launcher: ^6.1.10
  intl: ^0.20.2

  image_picker: ^1.0.7
  http: ^1.2.1
  crypto: ^3.0.3
  path: ^1.9.0
  qr_flutter: ^4.1.0
  fl_chart: ^0.64.0
  flutter_localizations:
    sdk: flutter
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
